export default [
    {
        image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUDSjr5zi_TrugjkknuHDH1jZFU2_3D0WZEA&usqp=CAU",
        title : 'BSC Sample Paper 1',
        length : 10,
        paperDescription : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam tenetur ex assumenda, eligendi minus est voluptatum laudantium sint delectus voluptas. Sit quas dignissimos assumenda, eligendi dicta provident cupiditate iste minus!',
        Language  : 'English',
        fileSize : '1.5MB',
        simultaneousDeviceUsage:1,
        author : 'M.Asnan',
        profile : 'https://i.stack.imgur.com/l60Hf.png',
        authorDescription : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde cum aperiam dolor, tempora quod rem delectus, eum quia doloribus eaque maxime quibusdam architecto vero aspernatur possimus temporibus voluptates ducimus excepturi?'
    },
    {
        image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKMHtwxxi36nqgadmXuT29Is95iHaUdYFSYw&usqp=CAU",
        title : 'BSC Sample Paper 2',
        length : 10,
        paperDescription : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam tenetur ex assumenda, eligendi minus est voluptatum laudantium sint delectus voluptas. Sit quas dignissimos assumenda, eligendi dicta provident cupiditate iste minus!',
        Language  : 'English',
        fileSize : '1.0MB',
        simultaneousDeviceUsage:1,
        author : 'M.Asnan',
        profile : 'https://i.stack.imgur.com/l60Hf.png',
        authorDescription : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde cum aperiam dolor, tempora quod rem delectus, eum quia doloribus eaque maxime quibusdam architecto vero aspernatur possimus temporibus voluptates ducimus excepturi?'
    },
    {
        image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-KcKq8PZcwvj17IAmsZwjGLEmbmwV5T1MNg&usqp=CAU",
        title : 'BSC Sample Paper 3 ',
        length : 10,
        paperDescription : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam tenetur ex assumenda, eligendi minus est voluptatum laudantium sint delectus voluptas. Sit quas dignissimos assumenda, eligendi dicta provident cupiditate iste minus!',
        Language  : 'English',
        fileSize : '1.0MB',
        simultaneousDeviceUsage:1,
        author : 'M.Asnan',
        profile : 'https://i.stack.imgur.com/l60Hf.png',
        authorDescription : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde cum aperiam dolor, tempora quod rem delectus, eum quia doloribus eaque maxime quibusdam architecto vero aspernatur possimus temporibus voluptates ducimus excepturi?'
    },
    {
        image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2GdJtoDyZx8hNfjf1RW_dHU-SsBrATne5Wg&usqp=CAU",
        title : 'BSC Sample Paper 4',
        length : 10,
        paperDescription : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam tenetur ex assumenda, eligendi minus est voluptatum laudantium sint delectus voluptas. Sit quas dignissimos assumenda, eligendi dicta provident cupiditate iste minus!',
        Language  : 'English',
        fileSize : '1.4MB',
        simultaneousDeviceUsage:1,
        author : 'M.Asnan',
        profile : 'https://i.stack.imgur.com/l60Hf.png',
        authorDescription : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde cum aperiam dolor, tempora quod rem delectus, eum quia doloribus eaque maxime quibusdam architecto vero aspernatur possimus temporibus voluptates ducimus excepturi?'
    },
    {
        image : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQECxqQxN1CF8B1qcgXePf2L9ux_ks8GnSsMA&usqp=CAU',
        title : 'BSC Sample Paper 5',
        length : 10,
        paperDescription : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam tenetur ex assumenda, eligendi minus est voluptatum laudantium sint delectus voluptas. Sit quas dignissimos assumenda, eligendi dicta provident cupiditate iste minus!',
        Language  : 'English',
        fileSize : '2.0MB',
        simultaneousDeviceUsage:1,
        author : 'M.Asnan',
        profile : 'https://i.stack.imgur.com/l60Hf.png',
        authorDescription : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde cum aperiam dolor, tempora quod rem delectus, eum quia doloribus eaque maxime quibusdam architecto vero aspernatur possimus temporibus voluptates ducimus excepturi?'
    },
    {
        image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzH6AaLZMKlRjQ_i3PGdGusZnQr-6ElxDvGg&usqp=CAU",
        title : 'BSC Sample Paper 6',
        length : 10,
        paperDescription : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam tenetur ex assumenda, eligendi minus est voluptatum laudantium sint delectus voluptas. Sit quas dignissimos assumenda, eligendi dicta provident cupiditate iste minus!',
        Language  : 'English',
        fileSize : '1.0MB',
        simultaneousDeviceUsage:1,
        author : 'M.Asnan',
        profile : 'https://i.stack.imgur.com/l60Hf.png',
        authorDescription : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde cum aperiam dolor, tempora quod rem delectus, eum quia doloribus eaque maxime quibusdam architecto vero aspernatur possimus temporibus voluptates ducimus excepturi?'
    },
    {
        image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJTnp1179lHvIqT9-UFROZzEp9jgUjMsYABA&usqp=CAU",
        title : 'BSC Sample Paper 7',
        length : 10,
        paperDescription : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam tenetur ex assumenda, eligendi minus est voluptatum laudantium sint delectus voluptas. Sit quas dignissimos assumenda, eligendi dicta provident cupiditate iste minus!',
        Language  : 'English',
        fileSize : '1.6MB',
        simultaneousDeviceUsage:1,
        author : 'M.Asnan',
        profile : 'https://i.stack.imgur.com/l60Hf.png',
        authorDescription : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde cum aperiam dolor, tempora quod rem delectus, eum quia doloribus eaque maxime quibusdam architecto vero aspernatur possimus temporibus voluptates ducimus excepturi?'
    },
    {
        image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVSzdsH9ZB8NsPkNvU6mjTfNLtpzO6GU8-4w&usqp=CAU",
        title : 'BSC Sample Paper 8',
        length : 10,
        paperDescription : 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam tenetur ex assumenda, eligendi minus est voluptatum laudantium sint delectus voluptas. Sit quas dignissimos assumenda, eligendi dicta provident cupiditate iste minus!',
        Language  : 'English',
        fileSize : '1.5MB',
        simultaneousDeviceUsage:1,
        author : 'M.Asnan',
        profile : 'https://i.stack.imgur.com/l60Hf.png',
        authorDescription : 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Unde cum aperiam dolor, tempora quod rem delectus, eum quia doloribus eaque maxime quibusdam architecto vero aspernatur possimus temporibus voluptates ducimus excepturi?'
    },
]